"""add tariff fields

Revision ID: 85c7d6b52429
Revises: e3303e5b4691
Create Date: 2025-05-10 17:37:06.461495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c7d6b52429'
down_revision: Union[str, None] = 'e3303e5b4691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tariff', sa.String(), nullable=False))
    op.add_column('users', sa.Column('tariff_paid', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('advisors', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'advisors')
    op.drop_column('users', 'tariff_paid')
    op.drop_column('users', 'tariff')
    # ### end Alembic commands ###
