"""delete_gender_column

Revision ID: e3303e5b4691
Revises: 9251ec9f02b7
Create Date: 2025-05-10 12:21:34.278586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3303e5b4691'
down_revision: Union[str, None] = '9251ec9f02b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
